name: Update a file every minute

on:
  schedule:
  - cron: '0 0 * * *'
  workflow_dispatch:

permissions: 
  contents: write

jobs:
  update:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Append to file
        run: echo "sample text" >> sample_file

      - name: Commit and Push
        run: |
          git --version
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add -A
          git commit -m "Update file with some content"
          git push -u origin
